export enum FileStatus {
  'PENDING' = 'PENDING',
  'RUNNING' = 'RUNNING',
  'LOCAL_CHUNK_COMPONENT' = 'LOCAL_CHUNK_COMPONENT',
  'SERVER_CHUNK_SUCCESSFUL' = 'SERVER_CHUNK_SUCCESSFUL',
  'SERVER_CHUNK_ERROR' = 'SERVER_CHUNK_ERROR',
  'MERGING' = 'MERGING',
  'MERGE_SUCCESSFUL' = 'MERGE_SUCCESSFUL',
  'MERGE_FAIL' = 'MERGE_FAIL',
  'DELETE' = 'DELETE',
}

export enum GatherFileFlag {
  'SUCCESS' = 'SUCCESS',
  'FAIL' = 'FAIL',
  'GATHERING' = 'GATHERING',
}

export enum FileTopStatus {
    'RETRY' = 'RETRY',
    'FILERETRY' = 'FILERETRY'
}