import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>next-demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <ul>
          <li>
            <Link href="/file">
              <a>大文件上传，下载</a>
            </Link>
            <Link href="/promise">
              <a>promise</a>
            </Link>
          </li>
        </ul>
      </main>
    </div>
  );
};

export default Home;
