name: Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  next-build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v3

    - name: Setup Node.js
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        registry-url: 'http://registry.npm.taobao.org'

    - name: Install Dependencies
      run: npm ci
    
    - name: Build Static Resources
      run: npm run export

    - name: Upload Next Build         
    - uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: |
          .next
          public
        retention-days: 7     



