name: Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  next-build:

    runs-on: ubuntu-latest
    
    steps:
    - name: checkout Step1
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        registry-url: 'http://registry.npm.taobao.org'

    - name: Install Dependencies
      run: npm ci
    
    - name: Build Static Resources
      run: npm run export

    - name: Upload Next Build
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: |
          .next
          public
        retention-days: 7     


  docker-push:
    needs: next-build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Step2
      uses: actions/checkout@v3

    - name: Download next build
      uses: actions/download-artifact@v2
      with:
        name: build-output

    - name: Build image 
      env: 
        TAG: $(date +%s)
      run: |
        echo 2222222
        echo $TAG
        docker build . --file CI.Dockerfile
        docker tag next-demo:$TAG

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_ACCOUNT }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Image
      uses: docker/build-push-action@v3
      env: 
        TAG: $(date +%s)
      with:
        push: true
        tags: ${{secrets.DOCKER_HUB_ACCOUNT}}/next-demo:$TAG

